baseURL = "$HUGO_BASEURL"
title = "Art website"
# disableKinds = ["page", "section", "taxonomy", "term"]
theme = "razvan"
timeout = 60000

paginate = 3

[taxonomies]
event = "events"
artwork = "artworks"
theme = "themes"
size = "sizes"
year = "years"

# MENU --------------------------------
# -------------------------------------
[[menu.main]]
identifier = "gallery"
name = "Gallery"
url = "/artworks/gallery/"
weight = 1
[[menu.main]]
identifier = "bio"
name = "Bio"
url = "/biography/"
weight = 2
[[menu.main]]
identifier = "exhibition"
name = "Events"
url = "/events/"
weight = 2
[[menu.main]]
identifier = "contact"
name = "Contact"
url = "/contact/"
weight = 10
pre = "hiddenMobile"
post = "icons/envelope-heart.svg"


# SHORTCOES ---------------------------
# -------------------------------------
[markup.goldmark.renderer]
unsafe = true
# PARAMS ------------------------------
# -------------------------------------
[params]
name = "Cristina Lefter"
dev = 0
favicon = ""
site_logo = ""
theme = "xtheme-pink"
exhibitionEndDate = false
organizedBy = false
prose = "prose prose-brand dark:prose-invert prose-h1:font-serif prose-h1:font-normal prose-h2:font-serif prose-h3:font-serif prose-h4:font-serif prose-h5:font-bold prose-thead:font-bold prose-thead:font-serif"


# Studio MAP --------------------------
# -------------------------------------
map = "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d960.9816688026032!2d9.316523879708356!3d45.458918101019066!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4786c8db9732b8d1%3A0xd9b17eba02429b06!2sVia%20Veneto%2C%2020068%20San%20Bovio%20MI%2C%20Italia!5e1!3m2!1sit!2suk!4v1693039627186!5m2!1sit!2suk"

# FORM TEST ---------------------------
# -------------------------------------
action = "https://docs.google.com/forms/d/e/1FAIpQLSf0lsbqQyqDrQvc91fhwvYTaEcUwCo4b1IvyL4soXCsqWvZeA/formResponse" #Google form
fullName = "entry.56747525"
city = "entry.1296023716"
zip = "entry.1213787509"
country = "entry.1469085403"
message = "entry.1214340196"
source = "entry.1370247914"
price = "entry.672303994"
stock = "entry.1773149955"
recaptcha = "6LeSTNcnAAAAAGt9V-aDn8xMCNeh0JMIAX1TCE2B"

# FORM LIVE ---------------------------
# -------------------------------------
_action = "formResponse"                                #Google form
_fullName = "entry.1234567890"
_city = "entry.1234567890"
_zip = "entry.1234567890"
_country = "entry.1234567890"
_message = "entry.1234567890"
_source = "entry.1234567890"
_price = "entry.1234567890"
_stock = "entry.1234567890"
_recaptcha = "6LeSTNcnAAAAAGt9V-aDn8xMCNeh0JMIAX1TCE2B"

# SOCIAL ------------------------------
[[params.social]]
link = "https://www.facebook.com/cristina.lefter.92"
[[params.social]]
link = "https://www.instagram.com/cristina_lefter_artist/"
[[params.social]]

# [outputs]
# #gallery = ["html", "json"]
# page = ["html", "json"]
# list = ["html", "json"]
# single = ["html", "json"]


[module]
# [[module.mounts]]
# # Workaround for https://github.com/gohugoio/hugo/issues/6945
# source = "assets/scss/bootstrap/_vendor"
# target = "assets/scss/bootstrap/vendor"

[module.hugoVersion]
extended = false
min = "0.112.0"
[[module.imports]]
path = "github.com/cromozooom/calina"
[[module.mounts]]
source = "static"
target = "static"
[[module.mounts]]
source = "assets"
target = "assets"
[[module.mounts]]
source = "layouts"
target = "layouts"
[[module.mounts]]
source = "assets"
target = "assets"
[[module.mounts]]
source = "hugo_stats.json"
target = "assets/watching/hugo_stats.json"
